services:
  backend.dev:
    image: node:22
    container_name: nodenest.backend.dev
    working_dir: /app
    volumes:
      - .:/app
    user: "1000:1000"
    ports:
      - "${PORT}:${PORT}"
    tty: true