services:
  backend.dev:
    image: node:22
    container_name: nodenest.backend.dev
    working_dir: /app
    volumes:
      - .:/app
    user: "1000:1000"
    ports:
      - "${PORT}:${PORT}"
    tty: true

  database:
    image: postgres:17
    container_name: nodenest.database
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: